### ISSUE TITLE
CC Licenses: CC0?

### ISSUE THREAD

**Issue by jhollist** [kbroman/pkg_primer#2]
Karl,

really nice job on the primer.  I am going to point a lot of people here.

Had a question about the use of Creative Commons for code.  First, a caveat.  I know very little about licensing packages.  With that said, I have been using CC0 for my packages as of late.  From what I have read it isn't technically a license, but a public domain declaration.

Are there any issues you are aware of with using CC0 for packages? 

Cheers,
Jeff

**Comment by kbroman** [comment]
I was thinking of exactly this over the weekend. The @rOpenSci package I was working on, [aRxiv](https://github.com/ropensci/aRxiv) (inherited from @karthik), has a CC0 license, and I'd prefer to change it to [MIT](http://en.wikipedia.org/wiki/MIT_License) or [BSD](http://en.wikipedia.org/wiki/BSD_licenses).

Putting the code in the public domain is great, but in some states (e.g. Maryland) software is treated as a "good" (like a car), and so if your code causes something terrible to happen, you could be sued for damages. Using a lenient license, like MIT or BSD, eliminates that potential problem through the "no warranty" clause.

**Comment by karthik** [comment]
CC0 is now a legacy license that the project is moving away from. I strongly support the move to MIT. Go ahead and change it, @kbroman

**Comment by jhollist** [comment]
@kbroman Thanks for the clarification.  

As you might imagine, working for the feds, we have some constraints on what we can and can't do.  They had us using an old NASA open source license that had some issues (again I am not aware of the details).  After many painful (but appreciated) calls with some of our general counsel staff, got them to agree to CC0.  There was some discussion that as federal employees we can't actually license the code as we have no claim to copyright and must release everything into the public domain. 

I may go back to them to see if they can't sign-off on our use of MIT.

**Comment by kbroman** [comment]
Cool, @karthik. It's [done](https://github.com/ropensci/aRxiv/pull/12). Tried to take a selfie, but the chrome extension can't find my camera. Dammit I'll just do it the old fashioned way.
![photo on 9-8-14 at 1 05 pm 2](https://cloud.githubusercontent.com/assets/53972/4190147/ce32b86a-3782-11e4-9ef1-b2761ea4cda8.jpg)

**Comment by kbroman** [comment]
@jhollist I'm rather surprised that they agreed to CC0.

**Comment by kbroman** [comment]
@karthik There was a little "github wants to use your camera request" up at the top. Oops.

**Comment by jhollist** [comment]
It may have been more along the lines of, "they didn't not agree to it"...[?]

Not really, they did agree.  It is better than what we had.

Also, we've been looking to both USGS and NASA as models as we try to
hammer out how, where and why we get to use Github/how we license our
software/etc.  It is a work in progress.  As of now we don't have too many
repositories public and a fairly small number of total users with EPA.

The change is slow, but happening (I think)...

Sorry for going off topic a bit on my original question.

On Mon, Sep 8, 2014 at 2:08 PM, Karl Broman notifications@github.com
wrote:

> @jhollist https://github.com/jhollist I'm rather surprised that they
> agreed to CC0.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kbroman/pkg_primer/issues/2#issuecomment-54862257.

## 

Jeff W. Hollister
email: jeff.w.hollister@gmail.com
google voice: 401 326 2531
cell: 401 556 4087

**Comment by kbroman** [comment]
Added discussion of CC0 to the [license page](http://kbroman.org/pkg_primer/pages/licenses.html) in [commit `a4e02bb`](https://github.com/kbroman/pkg_primer/commit/a4e02bbd3fc66102f76c8aea523356329e2ee0ce).

**Comment by jhollist** [comment]
Karl,

One last follow up on this.  I have been back and forth with our office of General Counsel.  They insist that we (EPA) are not able to enforce licenses, even those that are allow anything (yeah, WTFPL!) and thus have nothing to enforce. As such our options are to use a public domain dedication.   I am very close to getting an official sign off and change in our guidance on the use of Github to include the CC0 text as a requirement.  Best option for us given the situation.

In general, I think what you have written is great for your primary audience (i.e. not EPA) and no change is really needed.  I did want to point out that from what i can tell CC0 does have a no warranties clause ([section 4.b](https://wiki.creativecommons.org/CC0_FAQ#Does_using_CC0_affect_my_ability_to_disclaim_warranties.3F))  and thus it should protect against things like the Maryland example.  I think...

 I will now stop beating this horse.  Thanks again for a great tutorial!

Cheers,
Jeff

**Comment by kbroman** [comment]
Thanks for the update. The EPA lawyers continue to surprise.

**Comment by jhollist** [comment]
In both good and bad ways!
