### ISSUE TITLE
it's not clear how to install to a local directory

### ISSUE THREAD

**Issue by kcandrews** [kbroman/pkg_primer#3]
Thanks for your guide! I've found it helpful for coming to grips with the package structure, but after reading it, it's not clear how to actually install my package. As far as I can gather `R CMD install` only works if you either are developing the package inside of the system library (is that safe?) or you have root permissions. Guessing how to do this from reading an obsolete manual for `R CMD install` on the web, I tried installing my package following:

> http://stackoverflow.com/questions/29376107/trouble-installing-an-r-package-using-r-cmd-install

Perhaps giving an example for this common use case would be worth including?

**Comment by kbroman** [comment]
Good suggestion; I'll add an explanation along those lines.

**Comment by kbroman** [comment]
Added discussion of this point, in [this commit](https://github.com/kbroman/pkg_primer/commit/a4066b84e9c3379864a9a55be35886aa855b1129).
